// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { logger } from '@/lib/logger';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// CACHE BUSTER - ACTUALIZADO: 2024-05-05 11:20
logger.debug("[Supabase] Cliente conectado");

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  logger.error("[Supabase] ERROR CRÍTICO: Variables de entorno no detectadas.");
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {

  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});